package clinica.version_java.models.enums;

public enum Roles {
    ADMINISTRADOR,
    SOLO_LECTURA_TOTAL,
    ESCRITURA_LECTURA_TOTAL,
    SOLO_LECTURA_PACIENTE,
    ESCRITURA_LECTURA_PACIENTE,
    ESCRITURA_LECTURA_BORRADO_TOTAL
    
}
